### ISSUE TITLE
执行track_demo.py时未返回结果

### ISSUE THREAD

**Issue by Evan12306** [JackWoo0831/Yolov7-tracker#118]
(yolov8) D:\code\Yolov7-tracker-2>python tracker/track_demo.py --obj ../123.mp4 --detector yolov8 --tracker deepsort --kalman_format byte --detector_model_path ../yolov8n.pt --save_images
2024-10-27 21:40:50.106 | WARNING  | __main__:<module>:35 - No module named 'yolox'
2024-10-27 21:40:50.106 | WARNING  | __main__:<module>:36 - Load yolox fail. If you want to use yolox, please check the installation.
True
2024-10-27 21:40:51.020 | INFO     | __main__:main:165 - loading detector yolov8 checkpoint ../yolov8n.pt
2024-10-27 21:40:51.052 | INFO     | __main__:main:171 - loaded checkpoint done
Successfully loaded pretrained weights from "./weights/osnet_x0_25.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "D:\code\Yolov7-tracker-2\tracker\track_demo.py", line 269, in <module>
    main(args)
  File "D:\code\Yolov7-tracker-2\tracker\track_demo.py", line 257, in main
    save_results(folder_name=os.path.join(save_dir, 'txt_results'),
  File "D:\code\Yolov7-tracker-2\tracker\tracking_utils\tools.py", line 13, in save_results
    assert len(results)
AssertionError

ultralytics版本为8.094时报错ModuleNotFoundError: No module named  ultralytics.nn.modules.conv ;  ultralytics.nn.modules  is not a package，根据ultralytics的issue修改意见将版本升级至最新，results值为0

**Comment by JackWoo0831** [comment]
您好，我本地没有这个问题，请您参照一下[https://github.com/ultralytics/ultralytics/issues/3808](https://github.com/ultralytics/ultralytics/issues/3808)，如果您换到最新版没有输出检测结果，请您对照ultralytics的最新doc看一下和现有的代码有什么区别（尤其是导入模型和检测那几行）

**Comment by M3OT** [comment]
> (yolov8) D:\code\Yolov7-tracker-2>python tracker/track_demo.py --obj ../123.mp4 --detector yolov8 --tracker deepsort --kalman_format byte --detector_model_path ../yolov8n.pt --save_images 2024-10-27 21:40:50.106 | WARNING | **main**::35 - No module named 'yolox' 2024-10-27 21:40:50.106 | WARNING | **main**::36 - Load yolox fail. If you want to use yolox, please check the installation. True 2024-10-27 21:40:51.020 | INFO | **main**:main:165 - loading detector yolov8 checkpoint ../yolov8n.pt 2024-10-27 21:40:51.052 | INFO | **main**:main:171 - loaded checkpoint done Successfully loaded pretrained weights from "./weights/osnet_x0_25.pth" ** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias'] 0it [00:00, ?it/s] Traceback (most recent call last): File "D:\code\Yolov7-tracker-2\tracker\track_demo.py", line 269, in main(args) File "D:\code\Yolov7-tracker-2\tracker\track_demo.py", line 257, in main save_results(folder_name=os.path.join(save_dir, 'txt_results'), File "D:\code\Yolov7-tracker-2\tracker\tracking_utils\tools.py", line 13, in save_results assert len(results) AssertionError
> 
> ultralytics版本为8.094时报错ModuleNotFoundError: No module named ultralytics.nn.modules.conv ; ultralytics.nn.modules is not a package，根据ultralytics的issue修改意见将版本升级至最新，results值为0

没有分类器是要把这个re-id模型换成deepsort的re-id模型才行，我一开始使用osnet模型也是报错

**Comment by Evan12306** [comment]
重装环境，执行track_demo.py后哪里报错安哪里，朋友numpy版本为2.0.2没错，我安装2.0.2后报错要求回退到1.X的版本。改为1.26.4后程序可以正常运行一半，然后报错：
Traceback (most recent call last):
  File "D:\code\tracker\Yolov7-tracker-3\tracker\tracker_usb_camera.py", line 235, in <module>
    main(args)
  File "D:\code\tracker\Yolov7-tracker-3\tracker\tracker_usb_camera.py", line 202, in main
    current_tracks = tracker.update(output, img, frame)
  File "D:\code\tracker\Yolov7-tracker-3\tracker\trackers\ocsort_tracker.py", line 105, in update
    matches, u_track, u_detection = observation_centric_association(
  File "D:\code\tracker\Yolov7-tracker-3\tracker\trackers\matching.py", line 236, in observation_centric_association
    iou_matrix = bbox_ious(trk_tlbrs, det_tlbrs)
  File "src\\cython_bbox.pyx", line 17, in cython_bbox.bbox_overlaps
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)

**Comment by ElliottZhen** [comment]
请问assert len(results)，AssertionError这个解决了吗？

**Comment by JackWoo0831** [comment]
@ElliottZhen 您好这可能是由于没有检测或者跟踪结果导致的，最近会更新版本，我一并解决这个bug
