### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chenshengyeah111** [JackWoo0831/Yolov7-tracker#119]
Traceback (most recent call last):
  File "/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/tracker/track.py", line 326, in <module>
    main(args, cfgs)
  File "/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/tracker/track.py", line 254, in main
    output = model(img.cuda())
  File "/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/utils/torch_utils.py", line 372, in forward
    out = self.model(x.cuda())
  File "/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/conv.py(453): _conv_forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/conv.py(457): forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1130): _call_impl
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/models/common.py(2113): forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1130): _call_impl
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/models/common.py(2060): forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1130): _call_impl
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/models/yolo.py(345): forward_once
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/models/yolo.py(319): forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/nn/modules/module.py(1130): _call_impl
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/jit/_trace.py(967): trace_module
/home/imu_tcxn1/.conda/envs/v7tracker/lib/python3.9/site-packages/torch/jit/_trace.py(750): trace
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/utils/torch_utils.py(362): __init__
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/tracker/track.py(172): main
/ddnstor/imu_tcxn1/Hao/Toddler/Yolov7-tracker-2/tracker/track.py(326): <module>
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
这是为什么呀

**Comment by JackWoo0831** [comment]
这个错误有点奇怪呀，您是在用哪个detector的过程中出现的？您把检测模型也放到gpu上试一下，让读取的图片和模型都在一个device
