### ISSUE TITLE
追踪器测试问题

### ISSUE THREAD

**Issue by M3OT** [JackWoo0831/Yolov7-tracker#122]
我用yolo v7训练了自己的数据集
在接下来我想要测试追踪器的效果，我运行
python tracker/track.py --dataset duav --detector yolov7 --tracker deepsort --kalman_format byte --detector_model_path weights/best.pt --trace True --track_eval True

报错信息
Successfully loaded pretrained weights from "./weights/osnet_x0_25.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/track.py", line 316, in <module>
    main(args, cfgs)
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/track.py", line 291, in main
    save_results(folder_name=os.path.join(args.dataset, SPLIT), 
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/tracking_utils/tools.py", line 13, in save_results
    assert len(results)
AssertionError

我的数据集只有单类别

**Comment by M3OT** [comment]
我把re-id模型换成deepsort类，报错如下
2024-11-04 21:07:39.450 | INFO     | __main__:main:197 - Total 601 seqs will be tracked: ['.ipynb_checkpoints', '000001.PNG', '000002.PNG', '000003.PNG', '000004.PNG', '000005.PNG', '000006.PNG', '000007.PNG', '000008.PNG', '000009.PNG', '000010.PNG', '000011.PNG', '000012.PNG', '000013.PNG', '000014.PNG', '000015.PNG', '000016.PNG', '000017.PNG', '000018.PNG', '000019.PNG', '000020.PNG', '000021.PNG', '000022.PNG', '000023.PNG', '000024.PNG', '000025.PNG', '000026.PNG', '000027.PNG', '000028.PNG', '000029.PNG', '000030.PNG', '000031.PNG', '000032.PNG', '000033.PNG', '000034.PNG', '000035.PNG', '000036.PNG', '000037.PNG', '000038.PNG', '000039.PNG', '000040.PNG', '000041.PNG', '000042.PNG', '000043.PNG', '000044.PNG', '000045.PNG', '000046.PNG', '000047.PNG', '000048.PNG', '000049.PNG', '000050.PNG', '000051.PNG', '000052.PNG', '000053.PNG', '000054.PNG', '000055.PNG', '000056.PNG', '000057.PNG', '000058.PNG', '000059.PNG', '000060.PNG', '000061.PNG', '000062.PNG', '000063.PNG', '000064.PNG', '000065.PNG', '000066.PNG', '000067.PNG', '000068.PNG', '000069.PNG', '000070.PNG', '000071.PNG', '000072.PNG', '000073.PNG', '000074.PNG', '000075.PNG', '000076.PNG', '000077.PNG', '000078.PNG', '000079.PNG', '000080.PNG', '000081.PNG', '000082.PNG', '000083.PNG', '000084.PNG', '000085.PNG', '000086.PNG', '000087.PNG', '000088.PNG', '000089.PNG', '000090.PNG', '000091.PNG', '000092.PNG', '000093.PNG', '000094.PNG', '000095.PNG', '000096.PNG', '000097.PNG', '000098.PNG', '000099.PNG', '000100.PNG', '000101.PNG', '000102.PNG', '000103.PNG', '000104.PNG', '000105.PNG', '000106.PNG', '000107.PNG', '000108.PNG', '000109.PNG', '000110.PNG', '000111.PNG', '000112.PNG', '000113.PNG', '000114.PNG', '000115.PNG', '000116.PNG', '000117.PNG', '000118.PNG', '000119.PNG', '000120.PNG', '000121.PNG', '000122.PNG', '000123.PNG', '000124.PNG', '000125.PNG', '000126.PNG', '000127.PNG', '000128.PNG', '000129.PNG', '000130.PNG', '000131.PNG', '000132.PNG', '000133.PNG', '000134.PNG', '000135.PNG', '000136.PNG', '000137.PNG', '000138.PNG', '000139.PNG', '000140.PNG', '000141.PNG', '000142.PNG', '000143.PNG', '000144.PNG', '000145.PNG', '000146.PNG', '000147.PNG', '000148.PNG', '000149.PNG', '000150.PNG', '000151.PNG', '000152.PNG', '000153.PNG', '000154.PNG', '000155.PNG', '000156.PNG', '000157.PNG', '000158.PNG', '000159.PNG', '000160.PNG', '000161.PNG', '000162.PNG', '000163.PNG', '000164.PNG', '000165.PNG', '000166.PNG', '000167.PNG', '000168.PNG', '000169.PNG', '000170.PNG', '000171.PNG', '000172.PNG', '000173.PNG', '000174.PNG', '000175.PNG', '000176.PNG', '000177.PNG', '000178.PNG', '000179.PNG', '000180.PNG', '000181.PNG', '000182.PNG', '000183.PNG', '000184.PNG', '000185.PNG', '000186.PNG', '000187.PNG', '000188.PNG', '000189.PNG', '000190.PNG', '000191.PNG', '000192.PNG', '000193.PNG', '000194.PNG', '000195.PNG', '000196.PNG', '000197.PNG', '000198.PNG', '000199.PNG', '000200.PNG', '000201.PNG', '000202.PNG', '000203.PNG', '000204.PNG', '000205.PNG', '000206.PNG', '000207.PNG', '000208.PNG', '000209.PNG', '000210.PNG', '000211.PNG', '000212.PNG', '000213.PNG', '000214.PNG', '000215.PNG', '000216.PNG', '000217.PNG', '000218.PNG', '000219.PNG', '000220.PNG', '000221.PNG', '000222.PNG', '000223.PNG', '000224.PNG', '000225.PNG', '000226.PNG', '000227.PNG', '000228.PNG', '000229.PNG', '000230.PNG', '000231.PNG', '000232.PNG', '000233.PNG', '000234.PNG', '000235.PNG', '000236.PNG', '000237.PNG', '000238.PNG', '000239.PNG', '000240.PNG', '000241.PNG', '000242.PNG', '000243.PNG', '000244.PNG', '000245.PNG', '000246.PNG', '000247.PNG', '000248.PNG', '000249.PNG', '000250.PNG', '000251.PNG', '000252.PNG', '000253.PNG', '000254.PNG', '000255.PNG', '000256.PNG', '000257.PNG', '000258.PNG', '000259.PNG', '000260.PNG', '000261.PNG', '000262.PNG', '000263.PNG', '000264.PNG', '000265.PNG', '000266.PNG', '000267.PNG', '000268.PNG', '000269.PNG', '000270.PNG', '000271.PNG', '000272.PNG', '000273.PNG', '000274.PNG', '000275.PNG', '000276.PNG', '000277.PNG', '000278.PNG', '000279.PNG', '000280.PNG', '000281.PNG', '000282.PNG', '000283.PNG', '000284.PNG', '000285.PNG', '000286.PNG', '000287.PNG', '000288.PNG', '000289.PNG', '000290.PNG', '000291.PNG', '000292.PNG', '000293.PNG', '000294.PNG', '000295.PNG', '000296.PNG', '000297.PNG', '000298.PNG', '000299.PNG', '000300.PNG', '000301.PNG', '000302.PNG', '000303.PNG', '000304.PNG', '000305.PNG', '000306.PNG', '000307.PNG', '000308.PNG', '000309.PNG', '000310.PNG', '000311.PNG', '000312.PNG', '000313.PNG', '000314.PNG', '000315.PNG', '000316.PNG', '000317.PNG', '000318.PNG', '000319.PNG', '000320.PNG', '000321.PNG', '000322.PNG', '000323.PNG', '000324.PNG', '000325.PNG', '000326.PNG', '000327.PNG', '000328.PNG', '000329.PNG', '000330.PNG', '000331.PNG', '000332.PNG', '000333.PNG', '000334.PNG', '000335.PNG', '000336.PNG', '000337.PNG', '000338.PNG', '000339.PNG', '000340.PNG', '000341.PNG', '000342.PNG', '000343.PNG', '000344.PNG', '000345.PNG', '000346.PNG', '000347.PNG', '000348.PNG', '000349.PNG', '000350.PNG', '000351.PNG', '000352.PNG', '000353.PNG', '000354.PNG', '000355.PNG', '000356.PNG', '000357.PNG', '000358.PNG', '000359.PNG', '000360.PNG', '000361.PNG', '000362.PNG', '000363.PNG', '000364.PNG', '000365.PNG', '000366.PNG', '000367.PNG', '000368.PNG', '000369.PNG', '000370.PNG', '000371.PNG', '000372.PNG', '000373.PNG', '000374.PNG', '000375.PNG', '000376.PNG', '000377.PNG', '000378.PNG', '000379.PNG', '000380.PNG', '000381.PNG', '000382.PNG', '000383.PNG', '000384.PNG', '000385.PNG', '000386.PNG', '000387.PNG', '000388.PNG', '000389.PNG', '000390.PNG', '000391.PNG', '000392.PNG', '000393.PNG', '000394.PNG', '000395.PNG', '000396.PNG', '000397.PNG', '000398.PNG', '000399.PNG', '000400.PNG', '000401.PNG', '000402.PNG', '000403.PNG', '000404.PNG', '000405.PNG', '000406.PNG', '000407.PNG', '000408.PNG', '000409.PNG', '000410.PNG', '000411.PNG', '000412.PNG', '000413.PNG', '000414.PNG', '000415.PNG', '000416.PNG', '000417.PNG', '000418.PNG', '000419.PNG', '000420.PNG', '000421.PNG', '000422.PNG', '000423.PNG', '000424.PNG', '000425.PNG', '000426.PNG', '000427.PNG', '000428.PNG', '000429.PNG', '000430.PNG', '000431.PNG', '000432.PNG', '000433.PNG', '000434.PNG', '000435.PNG', '000436.PNG', '000437.PNG', '000438.PNG', '000439.PNG', '000440.PNG', '000441.PNG', '000442.PNG', '000443.PNG', '000444.PNG', '000445.PNG', '000446.PNG', '000447.PNG', '000448.PNG', '000449.PNG', '000450.PNG', '000451.PNG', '000452.PNG', '000453.PNG', '000454.PNG', '000455.PNG', '000456.PNG', '000457.PNG', '000458.PNG', '000459.PNG', '000460.PNG', '000461.PNG', '000462.PNG', '000463.PNG', '000464.PNG', '000465.PNG', '000466.PNG', '000467.PNG', '000468.PNG', '000469.PNG', '000470.PNG', '000471.PNG', '000472.PNG', '000473.PNG', '000474.PNG', '000475.PNG', '000476.PNG', '000477.PNG', '000478.PNG', '000479.PNG', '000480.PNG', '000481.PNG', '000482.PNG', '000483.PNG', '000484.PNG', '000485.PNG', '000486.PNG', '000487.PNG', '000488.PNG', '000489.PNG', '000490.PNG', '000491.PNG', '000492.PNG', '000493.PNG', '000494.PNG', '000495.PNG', '000496.PNG', '000497.PNG', '000498.PNG', '000499.PNG', '000500.PNG', '000501.PNG', '000502.PNG', '000503.PNG', '000504.PNG', '000505.PNG', '000506.PNG', '000507.PNG', '000508.PNG', '000509.PNG', '000510.PNG', '000511.PNG', '000512.PNG', '000513.PNG', '000514.PNG', '000515.PNG', '000516.PNG', '000517.PNG', '000518.PNG', '000519.PNG', '000520.PNG', '000521.PNG', '000522.PNG', '000523.PNG', '000524.PNG', '000525.PNG', '000526.PNG', '000527.PNG', '000528.PNG', '000529.PNG', '000530.PNG', '000531.PNG', '000532.PNG', '000533.PNG', '000534.PNG', '000535.PNG', '000536.PNG', '000537.PNG', '000538.PNG', '000539.PNG', '000540.PNG', '000541.PNG', '000542.PNG', '000543.PNG', '000544.PNG', '000545.PNG', '000546.PNG', '000547.PNG', '000548.PNG', '000549.PNG', '000550.PNG', '000551.PNG', '000552.PNG', '000553.PNG', '000554.PNG', '000555.PNG', '000556.PNG', '000557.PNG', '000558.PNG', '000559.PNG', '000560.PNG', '000561.PNG', '000562.PNG', '000563.PNG', '000564.PNG', '000565.PNG', '000566.PNG', '000567.PNG', '000568.PNG', '000569.PNG', '000570.PNG', '000571.PNG', '000572.PNG', '000573.PNG', '000574.PNG', '000575.PNG', '000576.PNG', '000577.PNG', '000578.PNG', '000579.PNG', '000580.PNG', '000581.PNG', '000582.PNG', '000583.PNG', '000584.PNG', '000585.PNG', '000586.PNG', '000587.PNG', '000588.PNG', '000589.PNG', '000590.PNG', '000591.PNG', '000592.PNG', '000593.PNG', '000594.PNG', '000595.PNG', '000596.PNG', '000597.PNG', '000598.PNG', '000599.PNG', '000600.PNG']
2024-11-04 21:07:39.450 | INFO     | __main__:main:209 - --------------tracking seq .ipynb_checkpoints--------------
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/track.py", line 316, in <module>
    main(args, cfgs)
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/track.py", line 291, in main
    save_results(folder_name=os.path.join(args.dataset, SPLIT), 
  File "/root/autodl-tmp/Yolov7-tracker-2/tracker/tracking_utils/tools.py", line 13, in save_results
    assert len(results)
AssertionError

**Comment by M3OT** [comment]
直接把这个文件.ipynb_checkpoints删除就可以解决了
