### ISSUE TITLE
cuda用不了，版本没问题，控制台torch是true，实际跑的时候报错

### ISSUE THREAD

**Issue by chenshangying1** [JackWoo0831/Yolov7-tracker#125]
F:\anaconda3\envs\yolo-tracker-v2\python.exe F:\python-env\Yolov7-tracker-2\tracker\track.py --dataset mot17 --detector yolov7 --tracker bytetrack --kalman_format byte --detector_model_path F:\python-env\Yolov7-tracker-2\weights\best.pt --save_images 
Traceback (most recent call last):
  File "F:\python-env\Yolov7-tracker-2\tracker\track.py", line 315, in <module>
    main(args, cfgs)
  File "F:\python-env\Yolov7-tracker-2\tracker\track.py", line 136, in main
    device = select_device(args.device)
  File "F:\python-env\Yolov7-tracker-2\utils\torch_utils.py", line 71, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
AssertionError: CUDA unavailable, invalid device 6 requested

**Comment by xiyunqiao** [comment]
加上--device "0"后，我的就可以用了
