### ISSUE TITLE
文件有权限报错

### ISSUE THREAD

**Issue by chenshangying1** [JackWoo0831/Yolov7-tracker#126]
文件有权限，不知道怎么改，一直报错
F:\anaconda3\envs\yolo-tracker-v2\python.exe F:\python-env\Yolov7-tracker-2\tracker\track.py --dataset mot17 --detector yolov7 --tracker bytetrack --kalman_format byte --detector_model_path F:\python-env\Yolov7-tracker-2\weights\best.pt --save_images --device 0 
2024-11-30 14:58:41.384 | INFO     | __main__:main:158 - loading detector yolov7 checkpoint F:\python-env\Yolov7-tracker-2\weights\best.pt
Fusing layers... 
 Convert model to Traced-model... 
 traced_script_module saved! 
 model is traced! 

2024-11-30 14:59:02.231 | INFO     | __main__:main:169 - loaded checkpoint done
2024-11-30 14:59:02.232 | INFO     | __main__:main:171 - Now detector is on device cuda:0
2024-11-30 14:59:02.232 | INFO     | __main__:main:196 - Total 21 seqs will be tracked: ['MOT17-01-DPM', 'MOT17-01-FRCNN', 'MOT17-01-SDP', 'MOT17-03-DPM', 'MOT17-03-FRCNN', 'MOT17-03-SDP', 'MOT17-06-DPM', 'MOT17-06-FRCNN', 'MOT17-06-SDP', 'MOT17-07-DPM', 'MOT17-07-FRCNN', 'MOT17-07-SDP', 'MOT17-08-DPM', 'MOT17-08-FRCNN', 'MOT17-08-SDP', 'MOT17-12-DPM', 'MOT17-12-FRCNN', 'MOT17-12-SDP', 'MOT17-14-DPM', 'MOT17-14-FRCNN', 'MOT17-14-SDP']
2024-11-30 14:59:02.232 | INFO     | __main__:main:208 - --------------tracking seq MOT17-01-DPM--------------
  0%|                                                                                                                           | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\python-env\Yolov7-tracker-2\tracker\track.py", line 315, in <module>
    main(args, cfgs)
  File "F:\python-env\Yolov7-tracker-2\tracker\track.py", line 224, in main
    for frame_idx, (ori_img, img) in process_bar:
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\python-env\Yolov7-tracker-2\tracker\tracker_dataloader.py", line 46, in __getitem__
    return self._getitem_yolov7(idx)
  File "F:\python-env\Yolov7-tracker-2\tracker\tracker_dataloader.py", line 64, in _getitem_yolov7
    img = cv2.imread(osp.join(self.seq_path, self.imgs_in_seq[idx])) 
  File "F:\anaconda3\envs\yolo-tracker-v2\lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
PermissionError: [Errno 13] Permission denied: 'F:\\python-env\\Yolov7-tracker-2\\data\\MOT17\\images\\test\\MOT17-01-DPM\\det'

**Comment by chenshangying1** [comment]
我换梯子之后就不报错了，什么原因呀

**Comment by JackWoo0831** [comment]
这个很奇怪，运行的过程中也没有下载的步骤，为什么换梯子就不报错了呢

**Comment by chenshangying1** [comment]
> 这个很奇怪，运行的过程中也没有下载的步骤，为什么换梯子就不报错了呢

是数据集的问题，用的v2版本convert转换数据集有点问题，不如master里的
