### ISSUE TITLE
关于代码track_demo.py的错误

### ISSUE THREAD

**Issue by zkzk123zk** [JackWoo0831/Yolov7-tracker#39]
您好，我在使用track_demo.py脚本时，使用自己的视频数据，程序运行后报错如下：
Traceback (most recent call last):
  File "tracker/track_demo.py", line 330, in <module>
    main(opts)
  File "tracker/track_demo.py", line 154, in main
    plot_img(img0, frame_id, [cur_tlwh, cur_id, cur_cls], save_dir=os.path.join(SAVE_FOLDER, 'reuslt_images', obj_name))
  File "tracker/track_demo.py", line 252, in plot_img
    text = f'{CATEGORY_DICT[cls]}-{id}'
KeyError: 3.0
请问是否为视频错误？

**Comment by JackWoo0831** [comment]
您好, 这是因为您需要指定代码开头的`CATEGORY_DICT`的值, 让它能根据类别的序号`0, 1, 2, 3...`对应出类别的名称, 请看代码开头的注释.

**Comment by koihoo** [comment]
您好，我指定了``CATEGORY_DICT`还是报错，（也是使用的自己的数据集）
```
Model summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
----------processing frame 0----------
Traceback (most recent call last):
  File "tracker/track_demo.py", line 337, in <module>
    main(opts)
  File "tracker/track_demo.py", line 160, in main
    plot_img(img0, frame_id, [cur_tlwh, cur_id, cur_cls], save_dir=os.path.join(SAVE_FOLDER, 'reuslt_images', obj_name))
  File "tracker/track_demo.py", line 258, in plot_img
    text = f'{CATEGORY_DICT[cls]}-{id}'
KeyError: 32500.0
``` 
在v8官方能正常进行追踪推理，请问这个怎么解决呢？
