### ISSUE TITLE
用yolov5自己训练的模型时运行track_demo.py时报错

### ISSUE THREAD

**Issue by w199809** [JackWoo0831/Yolov7-tracker#50]
您好，我自己对yolov5s.yaml做了改进，训练生成的模型放入track_demo.py时报错
Traceback (most recent call last):
  File "E:/BaiduNetdiskDownload/yolov7-tracker-master/tracker/track_demo.py", line 330, in <module>
    main(opts)
  File "E:/BaiduNetdiskDownload/yolov7-tracker-master/tracker/track_demo.py", line 117, in main
    out = model(img.to(device))  # model forward             
  File "D:\Can\anac_install\envs\torch_can\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\BaiduNetdiskDownload\yolov7-tracker-master\models\yolo.py", line 319, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\BaiduNetdiskDownload\yolov7-tracker-master\models\yolo.py", line 345, in forward_once
    x = m(x)  # run
  File "D:\Can\anac_install\envs\torch_can\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\BaiduNetdiskDownload\yolov7-tracker-master\models\yolo.py", line 54, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (84) must match the size of tensor b (48) at non-singleton dimension 2

Process finished with exit code 1
不知道问题在哪 想请教一下您  谢谢

**Comment by JackWoo0831** [comment]
可以的，自己训练的模型只是用来检测

**Comment by w199809** [comment]
好的   谢谢您
