### ISSUE TITLE
关于track_demo.py推理出错的问题

### ISSUE THREAD

**Issue by Minnchong** [JackWoo0831/Yolov7-tracker#85]
利用官方提供的best.pt推理视频时出错

D:\setup\anaconda\python.exe D:\code\project_code\Deepsort\code\Yolov7-tracker\tracker\track_demo.py 
Traceback (most recent call last):
  File "D:\code\project_code\Deepsort\code\Yolov7-tracker\tracker\track_demo.py", line 382, in <module>
    main(opts)
  File "D:\code\project_code\Deepsort\code\Yolov7-tracker\tracker\track_demo.py", line 69, in main
    ckpt = torch.load(opts.model_path, map_location=device)
  File "D:\setup\anaconda\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\setup\anaconda\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\setup\anaconda\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

进程已结束,退出代码1

请问是模型加载问题吗？

**Comment by JackWoo0831** [comment]
您好 您用的是yolov7吗
